### ISSUE TITLE
arrayify is not a function

### ISSUE THREAD

**Issue by FarisMarouane** [75lb/array-back#2]
Hello, thank you for your library.

I started however having the following error whenever I try to run my app: "TypeError: arrayify is not a function"

After spending some time trying to fix it, I could make it work by deleting the key "module": "./index.mjs" in your project's package.json.

From what I understood, in case of the existence of a module key in package.json, " [...], ES6-aware tools like Rollup and webpack 2 will import the ES6 module version directly." (https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for).

But something in my setup breaks this.

Here's my webpack config

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    target: 'node',
    entry: './src/index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'internetSpeed.js',
        library: 'internetSpeed',
        libraryTarget: 'umd',
    },
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        cacheDirectory: true,
                        presets: ['@babel/preset-env'],
                        plugins: [
                            '@babel/plugin-proposal-numeric-separator',
                            '@babel/plugin-proposal-optional-chaining',
                            '@babel/plugin-transform-runtime',
                            'syntax-dynamic-import',
                        ],
                    },
                },
            },
            {
                test: /\.random$/,
                use: [
                    {
                        loader: 'file-loader',
                    },
                ],
            },
        ],
    },
    plugins: [new webpack.BannerPlugin({ banner: '#!/usr/bin/env node', raw: true })],
    resolve: {
        extensions: ['.js'],
    },
    node: { fs: 'empty', net: 'empty', tls: 'empty', __dirname: false },
};
```

And package.json

```
{
    "name": "internet_speed_test",
    "version": "1.0.1",
    "description": "A simple command line tool to measure both download and upload internet speed",
    "main": "dist/internetSpeed.js",
    "files": [
        "dist"
    ],
    "scripts": {
        "start": "node dist/internetSpeed.js",
        "build:dev": "webpack --watch --config webpack.config.dev.js",
        "build:prod": "webpack --config webpack.config.prod.js",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [
        "internet",
        "speed"
    ],
    "homepage": "https://github.com/FarisMarouane/internetSpeedTest",
    "author": "Marouane Faris",
    "license": "ISC",
    "dependencies": {
        "@babel/runtime": "^7.8.4",
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "chalk": "^2.4.2",
        "command-line-usage": "^6.0.2",
        "external-ip": "^2.1.1",
        "haversine": "^1.1.1",
        "iplocation": "^6.1.0",
        "public-ip": "^3.2.0",
        "request": "^2.88.0"
    },
    "bin": {
        "internetSpeed": "./dist/internetSpeed.js"
    },
    "devDependencies": {
        "@babel/cli": "^7.8.4",
        "@babel/core": "^7.6.4",
        "@babel/plugin-proposal-numeric-separator": "^7.2.0",
        "@babel/plugin-proposal-optional-chaining": "^7.7.5",
        "@babel/plugin-transform-runtime": "^7.8.3",
        "@babel/preset-env": "^7.6.3",
        "babel-eslint": "^10.0.3",
        "babel-loader": "^8.0.6",
        "eslint": "^6.6.0",
        "eslint-config-prettier": "^6.5.0",
        "eslint-plugin-prettier": "^3.1.1",
        "file-loader": "^6.0.0",
        "prettier": "1.18.2",
        "terser-webpack-plugin": "^2.3.5",
        "webpack": "^4.41.6",
        "webpack-cli": "^3.3.11",
        "webpack-merge": "^4.2.2"
    }
}
```

I would really appreciate any help from your part. 

Thank you

**Comment by FarisMarouane** [comment]
I must add that I am not using "array-back" directly but through "command-line-usage"  which uses the 4.0.1 version ("array-back": "^4.0.1")

**Comment by 75lb** [comment]
Hi, are you on Windows or macOS? Which version node and npm are you using?

**Comment by 75lb** [comment]
will this rule exclude `.mjs` files? 

```
test: /\.js?$/,
```

**Comment by 75lb** [comment]
Node.js file are not always `.js`, they [maybe .cjs or .mjs too](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_determining_module_system)..

**Comment by FarisMarouane** [comment]
I am on: 
ubuntu 20.04.
Node: v14.17.0
npm: 6.14.13

**Comment by FarisMarouane** [comment]
I was thinking that maybe if command-line-usage used the latest version of array-back this issue would be fixed. I am still trying to make it work

**Comment by 75lb** [comment]
i will remove the `module` field from the package.json, give me 10 mins

**Comment by 75lb** [comment]
> will this rule exclude `.mjs` files?
> 
> ```
> test: /\.js?$/,
> ```

did you check this?

**Comment by 75lb** [comment]
I released a new version of array-back v4 which has the `module` field removed. Please update or reinstall your npm dependencies and try again.

**Comment by FarisMarouane** [comment]
I've just reinstalled all my dependencies and I still have the issue. I think it's because "command-line-usage" uses v4 and not the latest version of array-back

**Comment by FarisMarouane** [comment]
> check this?

Yes and it does exclude .mjs

**Comment by 75lb** [comment]
> I've just reinstalled all my dependencies and I still have the issue. I think it's because "command-line-usage" uses v4 and not the latest version of array-back

command-line-usage v6 uses v4 of array-back.. i have updated the v4 version of array-back, so when you run `npm ls` you should now see v4.0.2 - this is the fixed version without a `module` property.

**Comment by 75lb** [comment]
> > check this?
> 
> Yes and it does exclude .mjs

like I said above, it should not exclude `.mjs` files as `array-back/index.mjs` is a `.mjs` file.

**Comment by FarisMarouane** [comment]
> > > check this?
> > 
> > 
> > Yes and it does exclude .mjs
> 
> like I said above, it should not exclude `.mjs` files as `array-back/index.mjs` is a `.mjs` file.

**Comment by FarisMarouane** [comment]
Thank you !

**Comment by 75lb** [comment]
you're welcome, glad this is resolved 👍
